### ISSUE TITLE
Calling 'go group.Broadcasting(0)' results in tight loop

### ISSUE THREAD

**Issue by matthewmcneely** [grafov/bcast#4]
When invoking the Broadcasting method on a created Group with duration zero, the ```for``` loop in the function enters a tight loop. I believe this is because the test of

```go
case <-time.After(timeout):
```
is always satisfied when ```timeout``` is zero. I tested out the addition of the following routine in my local build. When called the CPU usage is back to normal:

```go
func (r *Group) ContinuousBroadcasting() {
	for {
		select {
		case received := <-r.in:
			switch received.payload.(type) {
			default: // receive a payload and broadcast it
				for _, member := range r.Members() {
					if received.sender != member { // not return broadcast to sender

						go func(out chan interface{}, received *Message) { // non blocking
							out <- received.payload
						}(member, &received)

					}
				}
			}
		}
	}
}

```

Let me know if you want a pull request, or perhaps you'd like to refactor the select statement in ```Broadcasting``` yourself. BTW, love the package. Thanks!

**Comment by raidoz** [comment]
I can confirm, that using go group.Broadcasting(0) causes high CPU load. Until fixed or for the next 100 years, I went with go group.Broadcasting(100*365*24*time.Hour).
