### ISSUE TITLE
tests fail on Go 1.5.1

### ISSUE THREAD

**Issue by ghost** [grafov/bcast#8]
Hey there, I was looking into your bcast library and noticed some tests fail on my machine with Go 1.5.1:

```
dq@empit:bcast$ go test -v
=== RUN   TestNewGroupAndJoin
--- PASS: TestNewGroupAndJoin (0.00s)
=== RUN   TestUnjoin
--- PASS: TestUnjoin (0.00s)
=== RUN   TestBroadcast
--- FAIL: TestBroadcast (0.10s)
    bcast_test.go:85: not all messages broadcasted
=== RUN   TestBroadcastFromMember
--- FAIL: TestBroadcastFromMember (0.10s)
    bcast_test.go:114: not all messages broadcasted
=== RUN   TestGroupBroadcast
--- FAIL: TestGroupBroadcast (0.15s)
    bcast_test.go:141: not all messages broadcasted
=== RUN   TestBroadcastOnLargeNumberOfMembers
--- FAIL: TestBroadcastOnLargeNumberOfMembers (1.05s)
    bcast_test.go:168: not all messages broadcasted (11267/16256)
FAIL
exit status 1
FAIL    github.com/grafov/bcast 1.415s
dq@empit:bcast$ go version
go version go1.5.1 linux/amd64
```

cheers/

**Comment by denquixote** [comment]
it works with Go 1.4.2, btw:
    dq@empit:bcast$ GOROOT=/opt/go1.4/ /opt/go1.4/bin/go test
    PASS
    ok  	github.com/grafov/bcast	1.569s
    dq@empit:bcast$ GOROOT=/opt/go1.4/ /opt/go1.4/bin/go version
    go version go1.4.2 linux/amd64

**Comment by grafov** [comment]
I'm not used this lib with Go 1.5 yet. I will check this bug. Thank for report.

**Comment by denquixote** [comment]
Academically I am very interested in how 1.4->1.5 could show a hidden concurrency bug. Is there a subtle race condition that didn't materialize on 1.4? Anyway, my use case is fault tolerant and I will use your lib since its implementation is as simple as it gets for my use case. So thanks for your lib and I'll keep an eye on this matter. :)
